name: Build and Deploy VitePress

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史记录以支持部署到分支

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run docs:build

      - name: Deploy to Deploy Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy # 部署到 deploy 分支
          folder: docs/.vitepress/dist # 构建产物目录
          clean: true # 部署前清理分支

      - name: Trigger Baota WebHook
        run: |
          # 触发宝塔 WebHook。
          # 建议在 GitHub Secrets 中设置 BT_WEBHOOK
          curl -k -X GET "${{ secrets.BT_WEBHOOK }}"
          echo "WebHook 触发成功！服务器将拉取已构建的版本。"
